#!/bin/bash

CONF="/etc/netwatch.conf"


test -s ${CONF} || exit 0
source ${CONF}

test -n "${NET_WATCH_HOST}" || exit 0
test -n "${NET_WATCH_PORT}" || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

test "${OS_NETWORKLESS}" == "true" && exit 0


watch() {
    sleep ${NET_WATCH_DELAY}

    count=0
    NET_WATCH_RETRIES=$((${NET_WATCH_RETRIES} - 1))
    while true; do
        sleep ${NET_WATCH_INTERVAL}
        if nc -z -w ${NET_WATCH_TIMEOUT} ${NET_WATCH_HOST} ${NET_WATCH_PORT} </dev/null >/dev/null 2>&1; then
            count=0
        else
            if [[ ${count} -lt ${NET_WATCH_RETRIES} ]]; then
                logger -t netwatch "cannot connect to ${NET_WATCH_HOST}:${NET_WATCH_PORT}"
                count=$((${count} + 1))
                continue
            else
                panic_action netwatch "cannot connect to ${NET_WATCH_HOST}:${NET_WATCH_PORT}"
            fi
        fi
    done
}

start() {
    msg_begin "Starting netwatch"
    watch &
    msg_done
}

stop() {
    msg_begin "Stopping netwatch"
    ps | grep netwatch | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
    msg_done
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;
        
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
