#!/bin/bash

CONF="/etc/connman/main.conf"
PROG="/usr/sbin/connmand"
PROG_WO="/usr/sbin/connmand-wait-online"
LOG="/var/log/connman.log"
LIB_DIR="/var/lib/connman"
RUN_DIR="/var/run/connman"
ONLINE_TIMEOUT=20


test -x ${PROG} || exit 0
test -s ${CONF} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Starting connman"

    mkdir -p ${RUN_DIR}
    ln -sf ${RUN_DIR}/resolv.conf /tmp/resolv.conf

    ifconfig lo up
    ${PROG} -n -r &> ${LOG} &
    if grep -qE '(Favorite)|(AutoConnect)=true' ${LIB_DIR}/*/settings 2>/dev/null; then
        ${PROG_WO} --timeout=${ONLINE_TIMEOUT}
        test $? == 0 && msg_done || msg_fail
    else
        msg_done
    fi
}

stop() {
    msg_begin "Stopping connman"
    killall -q $(basename ${PROG})
    msg_done
}


case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
