#!/bin/bash

SYS_CONF="/etc/openvpn"
BOOT_CONF="/boot/openvpn"
CONF="/data/etc/openvpn"

LOG="/var/log/openvpn.log"
PROG="/usr/sbin/openvpn"

WATCH_CONF="/data/etc/watch.conf"

LINK_WATCH=true


test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

prepare_conf ${CONF} ${SYS_CONF} ${BOOT_CONF}

test -s ${WATCH_CONF} && source ${WATCH_CONF}
test -d ${CONF} || exit 0


running() {
    killall -0 openvpn &> /dev/null
}

watch() {
    while true; do
        sleep 5
        if ! running; then
            logger -t openvpn "dead, calling panic action"
            panic_action openvpn
            break
        fi
    done
}

start() {
    msg_begin "Starting openvpn"
    modprobe tun

    ${PROG} --config ${CONF}/client.conf --cd ${CONF} &>>/var/log/openvpn.log &
    test $? == 0 && msg_done || msg_fail
    
    if [[ "${LINK_WATCH}" == "true" ]]; then
        watch &
    fi
}

stop() {
    msg_begin "Stopping openvpn"
    killall $(basename ${PROG}) &>/dev/null
    msg_done
}

case "$1" in
    start)
        start
        ;;
        
    stop)
        stop
        ;;
        
    restart)
        stop
        start
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
