#!/bin/bash

BRCM_PATCHRAM="/usr/libexec/brcm_patchram_plus1"
UART_DEV="/dev/ttyS1"
SARADC_IN1=$(cat /sys/bus/iio/devices/iio:device0/in_voltage1_raw)

if [[ "${SARADC_IN1}" -ge 634 ]] && [[ "${SARADC_IN1}" -le 746 ]]; then
    FIRMWARE_FILE="/lib/firmware/brcm/BCM4345C0.hcd"
else
    FIRMWARE_FILE="/lib/firmware/brcm/BCM4345C5.hcd"
fi

function btuart_start() {
    # Reset Bluetooth via GPIO
    echo "Blocking BT rfkill"
    rfkill block bluetooth
    sleep 1
    
    echo "Unblocking BT rfkill"
    rfkill unblock bluetooth
    sleep 1

    ${BRCM_PATCHRAM} --enable_hci --no2bytes --use_baudrate_for_download --tosleep 200000 --baudrate 1500000 --patchram ${FIRMWARE_FILE} ${UART_DEV}
}

function btuart_stop() {
    killall $(basename ${BRCM_PATCHRAM}) &>/dev/null
}
