#!/bin/bash

STATUS_LED="nanopi:blue:status"

case "$1" in
    start)
        echo 0 > /sys/class/leds/${STATUS_LED}/brightness
        echo 1 > /sys/class/leds/${STATUS_LED}/brightness
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
