#!/bin/bash

NET_LED="green:wan"

case "$1" in
    start)
        echo 0 > /sys/class/leds/${NET_LED}/brightness
        echo 1 > /sys/class/leds/${NET_LED}/brightness
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
