#!/bin/bash

OK_LED="green:lan"

case "$1" in
    start)
        echo 0 > /sys/class/leds/${OK_LED}/brightness
        echo 1 > /sys/class/leds/${OK_LED}/brightness
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
